version: '3'

networks:
  laravel:


services:
  app:
    container_name: '${APP_NAME:-laravel}_app'
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - laravel

  mysql:
    container_name: '${APP_NAME:-laravel}_mysql'
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-laravel}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-password}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    container_name: '${APP_NAME:-laravel}_php'
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '${PHP_PORT:-9000}:9000'
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  redis:
    container_name: '${APP_NAME:-laravel}_redis'
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - laravel

  composer:
    container_name: '${APP_NAME:-laravel}_composer'
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  npm:
    container_name: '${APP_NAME:-laravel}_npm'
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - '${NPM_PORT_1:-3000}:3000'
      - '${NPM_PORT_2:-3001}:3001'
      - '${NPM_PORT_3:-5173}:5173'
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel

  artisan:
    container_name: '${APP_NAME:-laravel}_artisan'
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel

  mailhog:
    container_name: '${APP_NAME:-laravel}_mailhog'
    image: mailhog/mailhog:latest
    ports:
      - '${MAILHOG_SMTP_PORT:-1025}:1025'
      - '${MAILHOG_HTTP_PORT:-8025}:8025'
    networks:
      - laravel


  phpmyadmin:
    container_name: '${APP_NAME:-laravel}_phpmyadmin'
    platform: linux/x86_64
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - '${PHPMYADMIN_PORT:-8080}:80'
    environment:
      MYSQL_USERNAME: '${DB_USERNAME:-laravel}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-laravel}'
      PMA_HOST: mysql
    networks:
    - laravel